//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKhamAnTam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionID { get; set; }
        public int RecordID { get; set; }
        public string MedicationName { get; set; }
        public string Dosage { get; set; }
        public string Duration { get; set; }
        public string Notes { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
